# Generated by Django 5.0 on 2023-12-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='permission',
            new_name='edit_permission',
        ),
        migrations.AddField(
            model_name='post',
            name='write_permission',
            field=models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('team', 'Team'), ('author', 'Author')], default='public', max_length=20),
        ),
    ]
