# Generated by Django 5.0 on 2023-12-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_permission_post_edit_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='write_permission',
            new_name='read_permission',
        ),
    ]
