# Generated by Django 5.0 on 2023-12-18 20:31

import django.core.validators
import django.utils.timezone
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_customuser_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
